SCHEMA_COMMANDS = [
    "WalkForward",
    "WalkBackward",
    "WalkLeft",
    "WalkRight",
    "Stop",
    "RotateLeft",
    "RotateRight",
    "Stand",
    "Sit",
    "ArmUnstow",
    "ArmStow",
    "GraspHand",
    "ReleaseHand",
    "ExtendArm",
]

PRIMITIVE_TO_SNIPPET = {
    "WalkForward": "walk_forward",
    "WalkBackward": "walk_backward",
    "WalkLeft": "walk_left",
    "WalkRight": "walk_right",
    "Stop": "stop",
    "RotateLeft": "rotate_left",
    "RotateRight": "rotate_right",
    "Stand": "stand",
    "Sit": "sit",
    "ArmUnstow": "arm_unstow",
    "ArmStow": "arm_stow",
    "GraspHand": "grasp_hand",
    "ReleaseHand": "release_hand",
    "ExtendArm": "extend_arm",
}

SUPPORTED_EXECUTION_SNIPPETS = {
    "walk_forward",
    "walk_backward",
    "walk_left",
    "walk_right",
    "rotate_left",
    "rotate_right",
    "stop",
    "arm_unstow",
    "arm_stow",
    "grasp_hand",
    "release_hand",
    "extend_arm",
}
